version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
