spring:
  application:
    name: delivery
# h2 ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret:
      key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
# swagger

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: asc
  paths-to-match: /api/**